apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: kubedata
resources:

# storage
- ./storage/minio
- ./storage/mysql
- ./storage/redis
- ./storage/postgresql
- ./storage/alluxio
#- ./storage/nfs

# compute
- ./compute/spark
- ./compute/trino

# apps
- ./apps/jupyter
- ./apps/superset

# commons
- ./common/traefik
- ./common/hivemetastore


