apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- dashboard-hook-ingressroute.yaml
- traefik-ui-ingressroute.yaml
- deployment.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- service.yaml
