---
apiVersion: v1
kind: List
metadata:
  name: traefik
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: traefik
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik
      ports:
      - port: 80
        name: web
        targetPort: "web"
        nodePort: 31000
        protocol: TCP
      - port: 443
        name: websecure
        targetPort: "websecure"
        protocol: TCP
