apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nfs-rbac.yaml
- nfs-storageclass.yaml
- nfs-client-deploy.yaml

configMapGenerator:
  - name: nfs-parameters
    namespace: kubeflow
    envs:
      - params.env
    options:
      disableNameSuffixHash: true

vars:
  - name: NFS_SERVER_IP
    objref:
      kind: ConfigMap
      name: nfs-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.NFS_SERVER_IP
  - name: NFS_SERVER_PATH
    objref:
      kind: ConfigMap
      name: nfs-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.NFS_SERVER_PATH



