---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    release: superset
