apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
spec:
  template:
    spec:
      initContainers:
      - command:
        - /bin/sh
        - -c
        - until nc -zv mysql 3306 -w1; do echo 'waiting for db'; sleep 3; done
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: wait-for-mysql
      containers:
      - name: hivemeta
        image: ghcr.io/hwk42/hivemetastore:3.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: rootPassword
        command: ["/opt/hive-metastore/bin/schematool"]
        args: ["--verbose" ,"-initSchema" , "-dbType", "mysql" , "-userName", "root",
          "-passWord", "$(MYSQL_ROOT_PASSWORD)" , "-url", 
          "jdbc:mysql://mysql:3306/metastore_db?createDatabaseIfNotExist=true&connectTimeout=1000&useSSL=false"]
      restartPolicy: Never
  backoffLimit: 1
