apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metastore.yaml
- hive-initschema.yaml

configMapGenerator:
  - name: metastore-cfg
    files:
      - metastore-site.xml
    options:
      disableNameSuffixHash: true


