---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-svc
spec:
  ports:
  - port: 9083
  selector:
    app: metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
spec:
  selector:
    matchLabels:
      app: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore
    spec:
      initContainers:
      - command:
        - /bin/sh
        - -c
        - i=0; until [ $((i)) -gt 0 ]; do echo 'waiting for bucket'; sleep 3;mc config host add kubedata http://minio-svc:9000 root kubedata123;i=`mc ls kubedata/kubedata |wc -l`;done
        image: minio/mc
        imagePullPolicy: IfNotPresent
        name: wait-for-bucket
      containers:
      - name: metastore
        image: ghcr.io/hwk42/hivemetastore:3.0.0
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretKey
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: metastore-cfg-vol
          mountPath: /opt/hive-metastore/conf/metastore-site.xml
          subPath: metastore-site.xml
        command: ["/opt/hive-metastore/bin/start-metastore"]
        args: ["-p", "9083"]
        imagePullPolicy: Always
      volumes:
        - name: metastore-cfg-vol
          configMap:
            name: metastore-cfg
